// <auto-generated />
namespace Aroma.BussinesLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Newssooqs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Newssooqs));
        
        string IMigrationMetadata.Id
        {
            get { return "202404271939415_Newssooqs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
