// <auto-generated />
namespace Aroma.BussinesLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class low : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(low));
        
        string IMigrationMetadata.Id
        {
            get { return "202404300737570_low"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
